pipeline:
  identifier: Build_Krishna_hub_spec_java_sample_1724189588123
  name: Build java_sample
  orgIdentifier: default
  projectIdentifier: Java__project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1724188462314
        repoName: Krishna-hub-spec/java_sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
              - parallel:
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Bash
                        command: <+input>
                  - step:
                      type: RunTests
                      name: RunTests_1
                      identifier: RunTests_1
                      spec:
                        language: Java
                        buildTool: Maven
                        args: "-DskipTests=true"
                        runOnlySelectedTests: true
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - "**/*.xml"
                        enableTestSplitting: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
